/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package groovy.bugs

// For demonstration purposes only, relies on System.currentTimeMillis
// and should probably not be merged.
class Groovy7873Bug extends GroovyTestCase {

    String bigString = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
Lorem ipsum
'''

    void testBugStripMarginGString() {
        def gstr = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
    Lorem upsum ${bigString}"""

        long i = System.currentTimeMillis()
        gstr.stripMargin()
        // Real time should be <10ms on avg.
        assert System.currentTimeMillis() - i < 100
    }

    void testBugStripIndentGString() {
        def gstr = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
    Lorem upsum ${bigString}"""

        long i = System.currentTimeMillis()
        gstr.stripIndent()
        // Real time should be <10ms on avg.
        assert System.currentTimeMillis() - i < 100
    }

    void testBugEachLineGString() {
        def gstr = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
    Lorem upsum ${bigString}"""

        long i = System.currentTimeMillis()
        gstr.eachLine {String line, int count -> }
        // Real time should be <10ms on avg.
        assert System.currentTimeMillis() - i < 100
    }

    void testBugDenormalizeGString() {
        def gstr = """Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis sed magna at nulla finibus pellentesque et posuere ligula. Mauris tempor facilisis convallis. Curabitur accumsan ligula placerat, venenatis turpis non, molestie mauris. Nullam vitae diam odio. Proin condimentum ultricies lectus, feugiat lacinia tortor feugiat laoreet. Aenean est dolor, condimentum at purus et, gravida tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent dui justo, pharetra vitae lacus at, pulvinar mattis mauris. Duis risus velit, facilisis non leo a, vehicula semper tortor. Quisque lacinia libero quam, a blandit massa eleifend quis. In sed ipsum at ex varius elementum tempus vitae libero. Nunc gravida nisi non urna viverra elementum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas pretium aliquet eros non fermentum.
    Lorem upsum ${bigString}"""

        long i = System.currentTimeMillis()
        gstr.denormalize()
        // Real time should be <10ms on avg.
        assert System.currentTimeMillis() - i < 100
    }
}
