= Groovy Podling Maturity Assessment

== Overview

This is an assessment of the Groovy podling's maturity, meant to help inform
the decision (of the mentors, community, Incubator PMC and ASF Board of 
Directors) to graduate it as a top-level Apache project.

It is based on the ASF project maturity model at
https://community.apache.org/apache-way/apache-project-maturity-model.html

Maintaining such a file is a new, experimental idea as part of the continuous
improvement of the ASF incubation process. Groovy is the first podling where 
that happens.

== Status of this document
At this point this is just a skeleton with the maturity items spelled out but
no detailed assessment.

== Overall assessment
Groovy looks ready to graduate, discussions and votes are ongoing on the project's
dev list as I write this (October 2015).

== Maturity model assessment 
Mentors and community members are encouraged to contribute to this 
and comment on it.

=== Code

==== CD10
_The project produces Open Source software, for distribution to the public at no charge._
 
==== CD20
_The project's code is easily discoverable and publicly accessible._

==== CD30
_The code can be built in a reproducible way using widely available standard tools._ 

==== CD40
_The full history of the project's code is available via a source code control system, in a way that allows any released version to be recreated._

==== CD50
_The provenance of each line of code is established via the source code control system, in a reliable way based on strong authentication of the committer._ When third-party contributions are committed, commit messages provide reliable information about the code provenance._ 

=== Licenses and Copyright

==== LC10
_The code is released under the Apache License, version 2._0._ 

==== LC20
_Libraries that are mandatory dependencies of the project's code do not create more restrictions than the Apache License does._ 

==== LC30
_The libraries mentioned in LC20 are available as Open Source software._ 

==== LC40
_Committers are bound by an Individual Contributor Agreement (the "Apache iCLA") that defines which code they are allowed to commit and how they need to identify code that is not their own._ 

==== LC50
_The copyright ownership of everything that the project produces is clearly defined and documented._

=== Releases

==== RE10
_Releases consist of source code, distributed using standard and open archive formats that are expected to stay readable in the long term._ 

==== RE20
_Releases are approved by the project's PMC (see CS10), in order to make them an act of the Foundation._ 

==== RE30
_Releases are signed and/or distributed along with digests that can be reliably used to validate the downloaded archives._ 

==== RE40
_Convenience binaries can be distributed alongside source code but they are not Apache Releases -- they are just a convenience provided with no guarantee._ 

=== Quality

==== QU10
_The project is open and honest about the quality of its code. Various levels of quality and maturity for various modules are natural and acceptable as long as they are clearly communicated._ 

==== QU20
_The project puts a very high priority on producing secure software._

==== QU30
_The project provides a well-documented channel to report security issues, along with a documented way of responding to them._ 

==== QU40
_The project puts a high priority on backwards compatibility and aims to document any incompatible changes and provide tools and documentation to help users transition to new features._ 

==== QU50
_The project strives to respond to documented bug reports in a timely manner._ 

=== Community

==== CO10
_The project has a well-known homepage that points to all the information required to operate according to this maturity model._ 

==== CO20
_The community welcomes contributions from anyone who acts in good faith and in a respectful manner and adds value to the project._ 

==== CO30
_Contributions include not only source code, but also documentation, constructive bug reports, constructive discussions, marketing and generally anything that adds value to the project._ 

==== CO40
_The community is meritocratic and over time aims to give more rights and responsibilities to contributors who add value to the project._ 

==== CO50
_The way in which contributors can be granted more rights such as commit access or decision power is clearly documented and is the same for all contributors._ 

==== CO60
_The community operates based on consensus of its members (see CS10) who have decision power. Dictators, benevolent or not, are not welcome in Apache projects._ 

==== CO70
_The project strives to answer user questions in a timely manner._ 

=== Consensus Building

==== CS10
_The project maintains a public list of its contributors who have decision power -- the project's PMC (Project Management Committee) consists of those contributors._ 

==== CS20
_Decisions are made by consensus among PMC members 9 and are documented on the project's main communications channel. Community opinions are taken into account but the PMC has the final word if needed._ 

==== CS30
_Documented voting rules are used to build consensus when discussion is not sufficient._ 

==== CS40
_In Apache projects, vetoes are only valid for code commits and are justified by a technical explanation, as per the Apache voting rules defined in CS30._ 

==== CS50
_All "important" discussions happen asynchronously in written form on the project's main communications channel. Offline, face-to-face or private discussions that affect the project are also documented on that channel._ 

=== Independence

==== IN10
_The project is independent from any corporate or organizational influence._ 

==== IN20
_Contributors act as themselves as opposed to representatives of a corporation or organization._ 