= Groovy Podling Maturity Assessment

== Overview

This is an assessment of the Groovy podling's maturity, meant to help inform
the decision (of the mentors, community, Incubator PMC and ASF Board of 
Directors) to graduate it as a top-level Apache project.

It is based on the ASF project maturity model at
https://community.apache.org/apache-way/apache-project-maturity-model.html

Maintaining such a file is a new, experimental idea as part of the continuous
improvement of the ASF incubation process. Groovy is the first podling where 
that happens.

== Status of this document
First evaluation done, lots of OK states below but also a number of TODO to resolve. 

== Overall assessment
Once the below _TODO_ are fixed (either by documenting the corresponding decisions or by
making the corresponding changes) Groovy looks ready to graduate, discussions and votes 
are ongoing on the project's dev list as I write this (October 2015).

== Maturity model assessment 
Mentors and community members are encouraged to contribute to this 
and comment on it.

=== Code

==== CD10
_The project produces Open Source software, for distribution to the public at no charge._

OK: of course.
 
==== CD20
_The project's code is easily discoverable and publicly accessible._

TODO: http://groovy.apache.org/ redirects to http://groovy-lang.org/, do we plan on keeping
it like that?

TODO: http://groovy-lang.org/ does not include an obvious link to the code repository (unless 
I missed something)

==== CD30
_The code can be built in a reproducible way using widely available standard tools._

OK: the build uses Gradle and continuous integration is used. 

==== CD40
_The full history of the project's code is available via a source code control system, in a way that allows any released version to be recreated._

OK: Using Git, main repository at https://git-wip-us.apache.org/repos/asf/incubator-groovy.git, releases are cut
from that repository.

==== CD50
_The provenance of each line of code is established via the source code control system, in a reliable way based on strong authentication of the committer.
When third-party contributions are committed, commit messages provide reliable information about the code provenance._

OK, see CD40 

=== Licenses and Copyright

==== LC10
_The code is released under the Apache License, version 2._0._ 

OK, LICENSE file has been accepted in release votes.

==== LC20
_Libraries that are mandatory dependencies of the project's code do not create more restrictions than the Apache License does._

TODO: do we have a documented verification of that? JIRA ticket? 

==== LC30
_The libraries mentioned in LC20 are available as Open Source software._

TODO: See LC20 

==== LC40
_Committers are bound by an Individual Contributor Agreement (the "Apache iCLA") that defines which code they are allowed to commit and how they need to identify code that is not their own._

OK, all committers have iCLAs on file. 

==== LC50
_The copyright ownership of everything that the project produces is clearly defined and documented._

OK, obvious for an ASF project.

=== Releases

==== RE10
_Releases consist of source code, distributed using standard and open archive formats that are expected to stay readable in the long term._

OK, verified in release votes.  

==== RE20
_Releases are approved by the project's PMC (see CS10), in order to make them an act of the Foundation._

OK, releases have been voted by the Incubator PMC. 

==== RE30
_Releases are signed and/or distributed along with digests that can be reliably used to validate the downloaded archives._

OK, verified in release votes. 

==== RE40
_Convenience binaries can be distributed alongside source code but they are not Apache Releases -- they are just a convenience provided with no guarantee._

TODO check the status of binaries in existing releases and briefly document it here.  

=== Quality

==== QU10
_The project is open and honest about the quality of its code. Various levels of quality and maturity for various modules are natural and acceptable as long as they are clearly communicated._ 

OK, Groovy has a long history of being a good citizen about quality.

==== QU20
_The project puts a very high priority on producing secure software._

OK, see QU10

==== QU30
_The project provides a well-documented channel to report security issues, along with a documented way of responding to them._

TODO: http://groovy-lang.org/ does not include that information as far as I can see. 
See also http://www.apache.org/foundation/marks/pmcs.html#navigation for required links on the project's homepage. 

==== QU40
_The project puts a high priority on backwards compatibility and aims to document any incompatible changes and provide tools and documentation to help users transition to new features._ 

OK, see QU10.

==== QU50
_The project strives to respond to documented bug reports in a timely manner._

OK, response times on the users list and jira are good. 

=== Community

==== CO10
_The project has a well-known homepage that points to all the information required to operate according to this maturity model._

TODO, see CD20 

==== CO20
_The community welcomes contributions from anyone who acts in good faith and in a respectful manner and adds value to the project._ 

OK, the community is working well in this respect. 

==== CO30
_Contributions include not only source code, but also documentation, constructive bug reports, constructive discussions, marketing and generally anything that adds value to the project._

OK, Groovy has elected some non-coding committers. 

==== CO40
_The community is meritocratic and over time aims to give more rights and responsibilities to contributors who add value to the project._

OK, Groovy has elected a few committers during incubation. 

==== CO50
_The way in which contributors can be granted more rights such as commit access or decision power is clearly documented and is the same for all contributors._

OK, based on the standard ASF docs. 

==== CO60
_The community operates based on consensus of its members (see CS10) who have decision power. Dictators, benevolent or not, are not welcome in Apache projects._

OK, demonstrated during incubation. 

==== CO70
_The project strives to answer user questions in a timely manner._

OK, see QU50. 

=== Consensus Building

==== CS10
_The project maintains a public list of its contributors who have decision power -- the project's PMC (Project Management Committee) consists of those contributors._

TODO, I don't think that list exists but it will eventually be at people.apache.org/committers-by-project.html#groovy-pmc
once the project graduates. 

==== CS20
_Decisions are made by consensus among PMC members and are documented on the project's main communications channel. Community opinions are taken into account but the PMC has the final word if needed._

OK, the Groovy team has been making and documenting decisions on its dev list during incubation.

==== CS30
_Documented voting rules are used to build consensus when discussion is not sufficient._ 

OK, using the standard ASF voting process, http://www.apache.org/foundation/voting.html

==== CS40
_In Apache projects, vetoes are only valid for code commits and are justified by a technical explanation, as per the Apache voting rules defined in CS30._

OK, vetoes haven't been abused during incubation. 

==== CS50
_All "important" discussions happen asynchronously in written form on the project's main communications channel. Offline, face-to-face or private discussions that affect the project are also documented on that channel._

OK, see CS20. 

=== Independence

==== IN10
_The project is independent from any corporate or organizational influence._

OK, no such influence has been detected during incubation. 

==== IN20
_Contributors act as themselves as opposed to representatives of a corporation or organization._

OK, no worrying signals here during incubation.  