//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= Performance

This subproject contains two sets of performance related tests, compiler tests
and benchmarks.

== Compiler Performance Tests

The compiler tests can be run using the following Gradle task:

    ./gradlew :perf:performanceTests

This will compile various source files using several past versions of Apache
Groovy in addition to the current source version.

== Benchmarks

JMH Benchmarks can be run using:

    ./gradlew :perf:jmh

In order to run the benchmarks against InvokeDynamic generated classes use
the `indy` property:

    ./gradlew -Pindy=true :perf:jmh

Groovy and Java sources placed in `src/test` will also be available to the
benchmarks.

To run a single benchmark or a matched set of benchmarks, use the
`benchInclude` property:

    ./gradlew -PbenchInclude=CallsiteBench :perf:jmh

The `benchInclude` property will perform a partial match against package
names or class names. It is equivalent to `.*${benchInclude}.*`.

