//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= Stress Tests

Tests in this subproject are used for stress testing.  These types of tests
will normally involve calls to `System.gc()`, spinning up many threads, and
may attempt to create OutOfMemory errors.

These tests can be long running and may be prone to failure on different
platforms, so in order to run these tests you must enable them as follows:

    ./gradlew -PstressTests :stress:test

You can run a single test with the following command:

    ./gradlew -PstressTests :stress:test --tests org.codehaus.groovy.util.SomeTest

Or run all tests under in a given package and subpackages:

    ./gradlew -PstressTests :stress:test --tests org.codehaus.*

