/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baulsupp_process_NativeProcess */

#ifndef _Included_com_baulsupp_process_NativeProcess
#define _Included_com_baulsupp_process_NativeProcess
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: initialised */
/*
 * Class:     com_baulsupp_process_NativeProcess
 * Method:    startProcess
 * Signature: (Ljava/lang/String;[Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_com_baulsupp_process_NativeProcess_startProcess
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
