//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= SaxBuilder

A builder for generating https://en.wikipedia.org/wiki/Simple_API_for_XML[Simple API for XML (SAX)] events.

If you have the following SAX handler:

[source,groovy]
----
include::{rootProjectDir}/subprojects/groovy-xml/src/spec/test/SaxBuilderTest.groovy[tags=sax_builder_handler,indent=0]
----

You can use `SaxBuilder` to generate SAX events for the handler like this:

[source,groovy]
----
include::{rootProjectDir}/subprojects/groovy-xml/src/spec/test/SaxBuilderTest.groovy[tags=sax_builder,indent=0]
----

And then check that everything worked as expected:

[source,groovy]
----
include::{rootProjectDir}/subprojects/groovy-xml/src/spec/test/SaxBuilderTest.groovy[tags=sax_builder_assert,indent=0]
----