= groovyc, the Groovy compiler
:toc:
:icons:
:linkcss!:

== Command-line compiler

`groovyc` is the Groovy compiler command line tool. It allows you to compile Groovy sources into bytecode. It plays
the same role as `javac` in the Java world. The easiest way to compile a Groovy script or class is to run the following command:

-----
groovyc MyClass.groovy
-----

This will produce a `MyClass.class` file (as well as other .class files depending on the contents of the source). `groovyc` supports
a number of command line switches:

[cols="<,<,<,<",options="header,footer"]
|=======================================================================
|Short version |Long version |Description |Example
|-cp |--classpath | Specify the compilation classpath. Must be the first
argument. | groovyc -cp lib/dep.jar MyClass.groovy
|-classpath | |Alias for -cp|
| |--sourcepath* |Directory where to find source files|groovyc -sourcepath src script.groovy
| |--temp |Temporary directory for the compiler |
| |--encoding |Encoding of the source files |groovyc -encoding utf-8 script.groovy
| |--help |Displays help for the command line groovyc tool |groovyc --help
|-v|--version|Displays the compiler version|groovyc -v
|-e|--exception|Displays the stack trace in case of compilation error|groovyc -e script.groovy
|-j|--jointCompilation*|Enables joint compilation|groovyc -j A.groovy B.java
|-b|--basescript|Base class name for scripts (must derive from Script)|
|-indy|--indy|Enables invokedynamic support. Requires Java 7+|groovyc --indy Person.groovy
||--configscript|Advanced compiler configuration script|groovyc --configscript config/config.groovy src/Person.groovy
|-Jproperty=value||Properties to be passed to `javac` if joint compilation is enabled|groovyc -j -Jtarget=1.5 -Jsource=1.5 A.groovy B.java
|-Fflag||Flags to be passed to `javac` if joint compilation is enabled|groovyc -j -Fnowarn A.groovy B.java
|=======================================================================

*Notes:*

* `sourcepath` is not used anymore. Specifying this parameter will have no effect on compilation.
* for a full description of joint compilation, see <<section-titles,Joint compilation>>

== Ant task

[[ThegroovycAntTask-groovyc]]
`<groovyc>`
~~~~~~~~~~~

[[ThegroovycAntTask-Description]]
Description
^^^^^^^^^^^

Compiles Groovy source files and, if joint compilation option is used, Java source files.

[[ThegroovycAntTask-Requiredtaskdef]]
Required taskdef
^^^^^^^^^^^^^^^^

Assuming `groovy-all-VERSION.jar` is in _my.classpath_ you will need to
declare this task at some point in the `build.xml` prior to the `groovyc`
task being invoked.

[source,xml]
----------------------------------------------------
<taskdef name="groovyc"
         classname="org.codehaus.groovy.ant.Groovyc"
         classpathref="my.classpath"/>
----------------------------------------------------

[[ThegroovycAntTask-groovycAttributes]]
<groovyc> Attributes
^^^^^^^^^^^^^^^^^^^^

[cols="<,<,<",options="header,footer"]
|=======================================================================
|Attribute |Description |Required

|srcdir |Location of the Groovy (and possibly Java) source files. |Yes

|destdir |Location to store the class files. |Yes

|classpath |The classpath to use. |No

|classpathref |The classpath to use given as a path references. |No

|sourcepath |The sourcepath to use. |No

|sourcepathref |The sourcepath to use given as a path reference. |No

|encoding |Encoding of source files. |No

|verbose |Asks the compiler for verbose output; defaults to no. |No

|includeAntRuntime |Whether to include the Ant run-time libraries in the
classpath; defaults to yes. |No

|includeJavaRuntime |Whether to include the default run-time libraries
from the executing VM in the classpath; defaults to no. |No

|fork |Whether to execute groovyc using a spawned instance of the JVM;
defaults to no. |No

|memoryInitialSize |The initial size of the memory for the underlying
VM, if using fork mode; ignored otherwise. Defaults to the standard VM
memory setting. (Examples: 83886080, 81920k, or 80m) |No

|memoryMaximumSize |The maximum size of the memory for the underlying
VM, if using fork mode; ignored otherwise. Defaults to the standard VM
memory setting. (Examples: 83886080, 81920k, or 80m) |No

|failonerror |Indicates whether compilation errors will fail the build;
defaults to true. |No

|listfiles |Indicates whether the source files to be compiled will be
listed; defaults to no. |No

|stacktrace |if true each compile error message will contain a
stacktrace |No

|indy |Enable compilation with the ``invoke dynamic'' support when using
Groovy 2.0 and beyond and running on JDK 7 |No

|scriptBaseClass |Sets the base class for Groovy scripts |No

|stubdir |Set the stub directory into which the Java source stub files should be generated. 
The directory need not exist and will not be deleted automatically - though its contents
will be cleared unless 'keepStubs' is true. Ignored when forked. |No

|keepStubs |Set the keepStubs flag. Defaults to false. Set to true for debugging.
Ignored when forked. |No

|forceLookupUnnamedFiles |The Groovyc Ant task is frequently used in the context of a build system
that knows the complete list of source files to be compiled. In such a
context, it is wasteful for the Groovy compiler to go searching the
classpath when looking for source files and hence by default the
Groovyc Ant task calls the compiler in a special mode with such searching
turned off. If you wish the compiler to search for source files then
you need to set this flag to true. Defaults to false. |No

|configscript |Set the configuration file used to customize the compilation configuration. |No

|=======================================================================

*Example:*

[source,xml]
----
<groovyc srcdir="src" destdir="target/classes">
</groovyc>
----


[[ThegroovycAntTask-groovycNestedElements]]
<groovyc> Nested Elements
^^^^^^^^^^^^^^^^^^^^^^^^^

[cols="<,<,<,<",options="header,footer"]
|==========================================================
|element |kind |Required |Replaces Attribute
|src |a path structure |Yes (unless srcdir is used) |srcdir
|classpath |a path structure |No |classpath
|javac |javac task |No |jointCompilationOptions
|==========================================================

*Notes:*

* For path structures see for example
http://ant.apache.org/manual/using.html#path
* For usages of the javac task see
http://ant.apache.org/manual/CoreTasks/javac.html
* The nested javac task behaves more or less as documented for the
top-level `javac` task. `srcdir`, `destdir`, `classpath`, `encoding` for the
nested `javac` task are taken from the enclosing `groovyc` task. If these
attributes are specified then they are added, they do not replace. In
fact, you should not attempt to overwrite the destination. Other
attributes and nested elements are unaffected, for example `fork`,
`memoryMaximumSize`, etc. may be used freely.

[[ThegroovycAntTask-JointCompilation]]
Joint Compilation
^^^^^^^^^^^^^^^^^

Joint compilation is enabled by using an embedded `javac` element, as shown in
the following example:

[source,xml]
----
<groovyc srcdir="${testSourceDirectory}" destdir="${testClassesDirectory}">
  <classpath>
    <pathelement path="${mainClassesDirectory}"/>
    <pathelement path="${testClassesDirectory}"/>
    <path refid="testPath"/>
  </classpath>
  <javac source="1.7" target="1.7" debug="on" />
</groovyc>
----

It is rare to specify `srcdir` and `destdir`, the nested `javac` task is provided with the `srcdir`
and `destdir` values from the enclosing `groovyc` task, and it is invariable
the right thing to do just to leave this as is.
To restate: the `javac` task gets the `srcdir`, `destdir` and `classpath` from
the enclosing `groovyc` task.

More details about joint compilation can be found in the <<section-titles,Joint compilation>> section.

== Maven integration
== GMaven and GMavenPlus
== The Groovy Eclipse Maven plugin

== Joint compilation

Joint compilation means that the Groovy compilation will parse the
Groovy source files, create stubs for all of them, invoke the Java
compiler to compile the stubs along with Java sources, and then continue
compilation in the normal Groovy compiler way. This allows mixing of
Java and Groovy files without constraint.

Joint compilation can be enabled using the `-j` flag with the command-line compiler,
or using using a nested tag and all the attributes and further nested tags as required
for the Ant task.

It is important to know that if you don't enable joint compilation and try to compile
Java source files with the Groovy compiler, the Java source files will be compiled as
if they were Groovy sources. In some situations, this might work since most of the Java
syntax is compatible with Groovy, but semantics would be different.

