/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.codehaus.groovy.ast.stmt;

import org.codehaus.groovy.ast.GroovyCodeVisitor;
import org.codehaus.groovy.ast.expr.ConstantExpression;
import org.codehaus.groovy.ast.expr.Expression;

import static org.codehaus.groovy.ast.tools.GeneralUtils.nullX;

/**
 * Represents a return statement that terminates a method and optionally returns a value.
 * A return statement evaluates the optional {@link #getExpression() return expression} and
 * returns control and the resulting value to the calling code. A return with no expression
 * returns null or void depending on the method signature.
 *
 * @see {@link ExpressionStatement}
 * @see {@link Statement}
 */
public class ReturnStatement extends Statement {
    /**
     * Only used for synthetic return statements emitted by the compiler.
     * For comparisons use isReturningNullOrVoid() instead.
     */
    public static final ReturnStatement RETURN_NULL_OR_VOID = new ReturnStatement(nullX());

    private Expression expression;

    /**
     * Constructs a return statement from an expression statement by extracting its expression.
     *
     * @param statement the {@link ExpressionStatement} whose expression will be returned
     */
    public ReturnStatement(final ExpressionStatement statement) {
        this(statement.getExpression());
        copyStatementLabels(statement);
    }

    /**
     * Constructs a return statement with the given return expression.
     *
     * @param expression the {@link Expression} to return, or null to return without a value
     */
    public ReturnStatement(final Expression expression) {
        setExpression(expression);
    }

    /**
     * Returns the expression whose value will be returned.
     *
     * @return the {@link Expression} to return, or null if returning without a value
     */
    public Expression getExpression() {
        return expression;
    }

    /**
     * Sets the expression whose value will be returned.
     *
     * @param expression the {@link Expression} to return
     */
    public void setExpression(final Expression expression) {
        this.expression = expression;
    }

    @Override
    public String getText() {
        return "return " + expression.getText();
    }

    /**
     * Checks whether this return statement returns null or void.
     * This method is used to identify implicit or synthetic return statements generated by the compiler.
     *
     * @return true if the return expression is a null constant; false otherwise
     */
    public boolean isReturningNullOrVoid() {
        return expression instanceof ConstantExpression
            && ((ConstantExpression) expression).isNullExpression();
    }

    @Override
    public String toString() {
        return super.toString() + "[expression:" + expression + "]";
    }

    @Override
    public void visit(final GroovyCodeVisitor visitor) {
        visitor.visitReturnStatement(this);
    }
}
