= Getting started
:toc:
:icons: font
:linkcss!:

== Download

In this download area, you will be able to download the distribution (binary and source), the Windows installer (for some of the versions) and the documentation for **Groovy**.

For a quick and effortless start on Mac OSX, Linux or Cygwin, you can use http://gvmtool.net[GVM] (the Groovy enVironment Manager) to download and configure any **Groovy** version of your choice. Basic link:#gvm-the-groovy-environment-manager[instructions] can be found below.

=== Groovy 2.1

Groovy 2 is the latest official major link:TODO[version of Groovy].

Learn more about Groovy 2.1 in the link:TODO[release notes].

==== Groovy 2.1.6

- **Download zip**: http://dist.groovy.codehaus.org/distributions/groovy-binary-2.1.6.zip[**Binary Release**] | http://dist.groovy.codehaus.org/distributions/groovy-src-2.1.6.zip[Source Release]
- **Download Windows-Installer**: http://dist.codehaus.org/groovy/distributions/installers/windows/nsis/groovy-2.1.6-installer.exe[**Binary Release**] http://dist.codehaus.org/groovy/distributions/installers/windows/nsis/installed_versions_2.1.6.txt[**(Module Versions)**]
- **Download documentation**: http://dist.groovy.codehaus.org/distributions/groovy-docs-2.1.6.zip[**JavaDoc and zipped online documentation**]
- **Combined binary / source / documentation bundle**: http://dist.groovy.codehaus.org/distributions/groovy-sdk-2.1.6.zip[**Distribution bundle**]

You can have a look at the http://jira.codehaus.org/secure/ReleaseNote.jspa?projectId=10242&version=19335[JIRA release notes].

If you plan on using invokedynamic support, link:TODO-InvokeDynamic+support[read those notes].

==== Groovy 2.1.5

- **Download zip**: http://dist.groovy.codehaus.org/distributions/groovy-binary-2.1.5.zip[**Binary Release**] | http://dist.groovy.codehaus.org/distributions/groovy-src-2.1.5.zip[Source Release]
- **Download Windows-Installer**: http://dist.codehaus.org/groovy/distributions/installers/windows/nsis/groovy-2.1.5-installer.exe[**Binary Release**] http://dist.codehaus.org/groovy/distributions/installers/windows/nsis/installed_versions_2.1.5.txt[**(Module Versions)**]
- **Download documentation**: http://dist.groovy.codehaus.org/distributions/groovy-docs-2.1.5.zip[**JavaDoc and zipped online documentation**]
- **Combined binary / source / documentation bundle**: http://dist.groovy.codehaus.org/distributions/groovy-sdk-2.1.5.zip[**Distribution bundle**]

You can have a look at the http://jira.codehaus.org/secure/ReleaseNote.jspa?projectId=10242&version=19320[JIRA release notes].

If you plan on using invokedynamic support, link:TODO-InvokeDynamic+support[read those notes].

=== Groovy 2.2

==== Groovy 2.2.0-beta-1

=== Groovy 2.0

==== Groovy 2.0.8

=== Groovy 1.8 (Maintenance Release)

==== Groovy 1.8.9

=== Snapshots

=== Older Releases

==== Groovy 1.7.11

==== Groovy 1.6.9

==== Groovy 1.5.8

=== Legacy Groovy 1.0


== Maven Repositories

=== Groovy 2.0.X  and newer

=== Groovy 1.6.X - 1.8.X

=== Groovy 1.1.X - 1.5.X

=== Groovy 1.0

=== Snapshot Releases


== GVM (the Groovy enVironment Manager)


== Other ways to get Groovy

=== Installation on Mac OS X

==== MacPorts

Set up http://www.macports.org[MacPorts] and type in the Terminal:

[source,shell]
----
sudo port install groovy
----

==== Homebrew

=== Installation on Windows

=== Other Distributions

=== Source Code

=== IDE plugin


== Install Binary

These instructions describe how to install a binary distribution of **Groovy**.

* First, link:#download-groovy[Download] a binary distribution of Groovy and unpack it into some file on your local file system.
* Set your ++GROOVY_HOME++ environment variable to the directory you unpacked the distribution.
* Add ++GROOVY_HOME/bin++ to your ++PATH++ environment variable.
* Set your ++JAVA_HOME++ environment variable to point to your JDK. On OS X this is ++/Library/Java/Home++, on other unixes its often ++/usr/java++ etc. If you've already installed tools like Ant or Maven you've probably already done this step.

You should now have Groovy installed properly. You can test this by typing the following in a command shell:

[source,shell]
----
groovysh
----

Which should create an interactive groovy shell where you can type Groovy statements. Or to run the link:tools/tools-groovyconsole.html[Swing interactive console] type:

[source,shell]
----
groovyConsole
----

To run a specific Groovy script type:

[source,shell]
----
groovy SomeScript.groovy
----
