= Getting started
:toc:
:icons: font
:linkcss!:

== Download Groovy

== Install Groovy

These instructions describe how to install a binary distribution of **Groovy**.

* First, link:#download-groovy[Download] a binary distribution of Groovy and unpack it into some file on your local file system.
* Set your ++GROOVY_HOME++ environment variable to the directory you unpacked the distribution.
* Add ++GROOVY_HOME/bin++ to your ++PATH++ environment variable.
* Set your ++JAVA_HOME++ environment variable to point to your JDK. On OS X this is ++/Library/Java/Home++, on other unixes its often ++/usr/java++ etc. If you've already installed tools like Ant or Maven you've probably already done this step.

You should now have Groovy installed properly. You can test this by typing the following in a command shell:

[source,shell]
----
groovysh
----

Which should create an interactive groovy shell where you can type Groovy statements. Or to run the link:tools/tools-groovyconsole.html[Swing interactive console] type:

[source,shell]
----
groovyConsole
----

To run a specific Groovy script type:

[source,shell]
----
groovy SomeScript.groovy
----

**Alternative Installation on Mac OS X**

Set up link:http://www.macports.org[MacPorts] and type in the Terminal:

[source,shell]
----
sudo port install groovy
----