= Syntax
:toc:
:icons: font
:linkcss!:

This chapter covers the syntax of the Groovy programming language.
The grammar of the language derives from the Java grammar,
but enhances it with specific constructs for Groovy, and allows certain simplifications.

== Comments

=== Single line comment

Single line comments start with +//+ and can be found at any position in the line.
The characters following +//+, till the end of the line, are considered part of the comment.

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=single_line_comment,indent=0]
----

=== Multiline comment

A multiline comment starts with +/*+ and can be found at any position in the line.
The characters following +/*+ will be considered part of the comment, including new line characters,
up to the first +*/+ closing the comment.
Multiline comments can thus be put at the end of a statement, or even inside a statement.

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=multiline_comment,indent=0]
----

=== JavaDoc comment
=== Shebang line

Beside the single line comment, there is a special line comment, often called the _shebang_ line understood by UNIX systems
which allows scripts to be run directly from the command-line, provided you have installed the Groovy distribution
and the +groovy+ command is available on the +PATH+.

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=shebang_comment_line,indent=0]
----

NOTE: The +#+ character must be the first character of the file. Any indentation would yield a compilation error.

== Keywords

The following list represents all the keywords of the Groovy language:

[cols="1,1,1,1"]
.Keywords
|===
|as
|assert
|break
|case

|catch
|class
|const
|continue

|def
|default
|do
|else

|enum
|extends
|false
|finally

|for
|goto
|if
|implements

|import
|in
|instanceof
|interface

|new
|null
|package
|return

|super
|switch
|this
|throw

|throws
|true
|try
|while

|===

== Identifiers

=== Normal identifiers

Identifiers start with a letter, a dollar or an underscore.
They cannot start with a number.

A letter can be in the following ranges:

* 'a' to 'z' (lowercase ascii letter)
* 'A' to 'Z' (uppercase ascii letter)
* '\u00C0' to '\u00D6'
* '\u00D8' to '\u00F6'
* '\u00F8' to '\u00FF'
* '\u0100' to '\uFFFE'

Then following characters can contain letters and numbers.

Here are a few examples of valid identifiers (here, variable names):

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=valid_identifiers,indent=0]
----

But the following ones are invalid identifiers:

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=invalid_identifiers,indent=0]
----

All keywords are also valid identifiers when following a dot:

[source,groovy]
----
include::../test/SyntaxTest.groovy[tags=keywords_valid_id_after_dot,indent=0]
----

=== Quoted identifiers



== Strings

=== Single quoted string
=== Double quoted string
=== Triple single quoted string
=== Triple double quoted string
=== Slashy string
=== Dollar slashy string

== Numbers

=== Integer literal
=== Floating point literal
=== Binary literal
=== Octal literal
=== Hexadecimal literal
=== Underscore in literal
=== Number type suffixes

== Booleans

== Arrays

== Lists

== Maps

=== String keys
=== Parenthesized keys
