= Object orientation

This chapter covers the object orientation of the Groovy programming language.

== Types (TBD)

=== Primitive types (TBD)

=== Class

Groovy classes are very similar to Java classes. Thus, they may have methods and fields/properties, are compatible with Java classes at JVM level, their elements can have the same modifiers (public, protected, private, static, synchronized, etc), and the imports and package declarations have the same syntax.

The first difference is the verbosity eliminated by turning fields into properties automatically. More on this aspect will be presented in the Section "Fields and properties". The second difference is that any property or method without an access modifier is public.

The following code presents an example class.


==== Normal class (MichaelSchuenck)
==== Static class (MichaelSchuenck)
==== Inner class (MichaelSchuenck)
===== Anonymous inner class (MichaelSchuenck)
==== Abstract class (MichaelSchuenck)

=== Interface (TBD)

=== Annotation (TBD)

==== Closure annotation parameters (TBD)
==== Meta-annotations (TBD)
==== Annotation placement (TBD)

=== Constructors (TBD)

==== Named argument constructor (TBD)

=== Methods (TBD)

==== Method definition (TBD)
==== Named arguments (TBD)
==== Default arguments (TBD)
==== Varargs (TBD)
==== Method selection algorithm (TBD)
==== Exception declaration (TBD)

=== Fields and properties (TBD)

==== Fields (TBD)
==== Properties (TBD)

=== Inheritance (TBD)

[[generics]]
=== Generics (TBD)

include::{projectdir}/src/spec/doc/core-traits.adoc[leveloffset=+1]

