= Semantics

This chapter covers the semantic of the Groovy programming language.

== Statements

=== Variable definition

Variables can be defined using either their type (like `String`) or by using the keyword `def`:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=variable_definition_example,indent=0]
----

`def` is a replacement for a type name. In variable definitions it is used to indicate that you don't care about the type. In variable definitions it is mandatory to either provide a type name explicitly or to use "def" in replacement. This is needed to the make variable definitions detectable for the Groovy parser.

You can think of `def` as an alias of `Object` and you will understand it in an instant.

=== Variable assignment

You can assign values to variables for later use. Try the following:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=variable_assignment_example,indent=0]
----

==== Multiple assignment

Groovy supports multiple assignment, i.e. where multiple variables can be assigned at once, e.g.:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_example,indent=0]
----

You can provide types as part of the declaration if you wish:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_with_types,indent=0]
----

As well as used when declaring variables it also applies to existing variables:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_with_existing_variables,indent=0]
----

The syntax works for arrays as well as lists, as well as methods that return either of these:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_with_arrays_and_lists,indent=0]
----

==== Overflow and Underflow

If the left hand side has too many variables, excess ones are filled with null's:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_underflow,indent=0]
----

If the right hand side has too many variables, the extra ones are ignored:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=multiple_assignment_overflow,indent=0]
----

=== Control structures (WIP)
==== Conditional structures
===== if / else

Groovy supports the usual if - else syntax from Java

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=if_else_example,indent=0]
----

Groovy also supports the normal Java "nested" if then else if syntax:

[source,groovy]
----
if ( ... ) {
    ...
} else if (...) {
    ...
} else {
    ...
}
----

===== switch / case

The switch statement in Groovy is backwards compatible with Java code; so you can fall through cases sharing the same code for multiple matches.

One difference though is that the Groovy switch statement can handle any kind of switch value and different kinds of matching can be performed.

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=switch_case_example,indent=0]
----

Switch supports the following kinds of comparisons:

* Class case values matches if the switch value is an instance of the class
* Regular expression case value matches if the string of the switch value matches the regex
* Collection case value matches if the switch value is contained in the collection. This also includes ranges (since they are Lists)
* If none of the above are used then the case value matches if the case value equals the switch value

NOTE: +default+ must go at the end of the switch/case. While in Java the default can be placed anywhere in the switch/case, the default in Groovy is used more as an else than assigning a default case.

==== Looping structures
===== Classic for loop

Groovy supports the standard Java / C for loop:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=classic_for_loop_example,indent=0]
----

===== for in loop

The for loop in Groovy is much simpler and works with any kind of array, collection, Map, etc.

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=groovy_for_loop_example,indent=0]
----

===== while loop

Groovy supports the usual while {...} loops like Java:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=while_loop_example,indent=0]
----

==== Exception handling

Exception handling is the same as Java.

==== try / catch / finally

You can specify a complete +try-catch-finally+, a +try-catch+, or a +try-finally+ set of blocks.

NOTE: Braces are required around each block's body.

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=try_catch_example,indent=0]
----

We can put code within a 'finally' clause following a matching 'try' clause, so that regardless of whether the code in the 'try' clause throws an exception, the code in the finally clause will always execute:

[source,groovy]
----
include::{projectdir}/src/spec/test/SemanticsTest.groovy[tags=try_catch_finally_example,indent=0]
----

==== Multi-catch

With the multi catch block (since Groovy 2.0), we're able to define several exceptions to be catch and treated by the same catch block:

[source,groovy]
----
try {
    /* ... */
} catch ( IOException | NullPointerException e ) {
    /* one block to handle 2 exceptions */
}
----

=== Power assertion (TBD)
=== Labeled statements (TBD)

== Expressions (TBD)

=== GPath expressions (TBD)

== Promotion and coercion (TBD)

=== Number promotion (TBD)
=== Closure to type coercion
==== Assigning a closure to a SAM type
A SAM type is a type which defines a single abstract method. This includes:

[source,groovy]
.Functional interfaces
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=filter_sam_type,indent=0]
----

[source,groovy]
.Abstract classes with single abstract method
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=greeter_sam_type,indent=0]
----

Any closure can be converted into a SAM type using the `as` operator:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=assertions_explicit_closure_to_sam,indent=0]
----

However, the `as Type` expression is optional since Groovy 2.2.0. You can omit it and simply write:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=assertions_implicit_closure_to_sam,indent=0]
----

which means you are also allowed to use method pointers, as shown in the following example:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=assertions_implicit_closure_to_sam_and_method_pointer,indent=0]
----

==== Calling a method accepting a SAM type with a closure

The second and probably more important use case for closure to SAM type coercion is calling a method which accepts
a SAM type. Imagine the following method:

[source,groovy]
-----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=method_accepting_filter,indent=0]
-----

Then you can call it with a closure, without having to create an explicit implementation of the interface:

[source,groovy]
-----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=method_call_with_explicit_coercion,indent=0]
-----

But since Groovy 2.2.0, you are also able to omit the explicit coercion and call the method as if it used a closure:

[source,groovy]
-----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=method_call_with_implicit_coercion,indent=0]
-----

As you can see, this has the advantage of letting you use the closure syntax for method calls, that is to say put the
closure outside of the parenthesis, improving the readability of your code.

==== Closure to arbitrary type coercion

In addition to SAM types, a closure can be coerced to any type and in particular interfaces. Let's define the
following interface:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=foobar_interface,indent=0]
----

You can coerce a closure into the interface using the `as` keyword:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=foobar2closure_coercion,indent=0]
----

This produces a class for which all methods are implemented using the closure:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=foobarintf_assertions,indent=0]
----

But it is also possible to coerce a closure to any class. For example, we can replace the `interface` that we defined
with `class` without changing the assertions:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=closure2foobarclass,indent=0]
----

=== Map to type coercion

Usually using a single closure to implement an interface or a class with multiple methods is not the way to go. As an
alternative, Groovy allows you to coerce a map into an interface or a class. In that case, keys of the map are
interpreted as method names, while the values are the method implementation. The following example illustrates the
coercion of a map into an `Iterator`:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=coerce_map_to_iterator,indent=0]
----

Of course this is a rather contrived example, but illustrates the concept. You only need to implement those methods
that are actually called, but if a method is called that doesn't exist in the map a `MissingMethodException` or an
`UnsupportedOperationException` is thrown, depending on the arguments passed to the call,
as in the following example:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=define_x_interface,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=call_existing_method,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=call_non_existing_method,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=call_notimplemented_method,indent=0]
----

The type of the exception depends on the call itself:

* `MissingMethodException` if the arguments of the call do not match those from the interface/class
* `UnsupportedOperationException` if the arguments of the call match one of the overloaded methods of the interface/class

=== String to enum coercion

Groovy allows transparent +String+ (or +GString+) to enum values coercion. Imagine you define the following enum:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=state_enum,indent=0]
----

then you can assign a string to the enum without having to use an explicit `as` coercion:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=enum_coerce_assignment,indent=0]
----

It is also possible to use a +GString+ as the value:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=enum_coerce_assignment_gstring,indent=0]
----


However, this would throw a runtime error (+IllegalArgumentException+):
[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=enum_coerce_assignment_wrong,indent=0]
----

Note that it is also possible to use implicit coercion in switch statements:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=enum_switch_method,indent=0]
----

in particular, see how the `case` use string constants. But if you call a method that uses an enum with a +String+
argument, you still have to use an explicit `as` coercion:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=enum_switch_test,indent=0]
----

=== Custom type coercion

It is possible for a class to define custom coercion strategies by implementing the +asType+ method. Custom coercion
is invoked using the `as` operator and is never implicit. As an example,
imagine you defined two classes, +Polar+ and +Cartesian+, like in the following example:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_header,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_footer,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=cartesian_class,indent=0]
----

And that you want to convert from polar coordinates to cartesian coordinates. One way of doing this is to define
the +asType+ method in the +Polar+ class:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_astype,indent=0]
----

which allows you to use the +as+ coercion operator:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_astype_assert,indent=0]
----

Putting it all together, the +Polar+ class looks like this:
[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_header,indent=0]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_astype,indent=4]
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_class_footer,indent=0]
----

but it is also possible to define +asType+ outside of the +Polar+ class, which can be practical if you want to define
custom coercion strategies for "closed" classes or classes for which you don't own the source code, for example using
a metaclass:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=polar_metaclass_astype,indent=0]
----

=== Class literals vs variables and the as operator

Using the `as` keyword is only possible if you have a static reference to a class, like in the following code:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=as_keyword,indent=0]
----

But what if you get the class by reflection, for example by calling `Class.forName`?

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=clazz_greeter_header,indent=0]
----

Trying to use the reference to the class with the `as` keyword would fail:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=incorrect_as_usage,indent=0]
----

It is failing because the `as` keyword only works with class literals. Instead, you need to call the `asType` method:

[source,groovy]
----
include::{projectdir}/src/spec/test/CoercionTest.groovy[tags=fixed_as_usage,indent=0]
----

== Optionality (TBD)

=== Optional parentheses (TBD)
=== Optional semicolons (TBD)
=== Optional return keyword (TBD)
=== Optional public keyword (TBD)

[[Groovy-Truth]]
== The Groovy Truth (TBD)

=== Customizing the truth with asBoolean() methods (TBD)

== Typing (WIP)

=== Optional typing

Optional typing is the idea that a program can work even if you don't put an explicit type on a variable. Being a dynamic
language, Groovy naturally implements that feature, for example when you declare a variable:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/OptionalTypingTest.groovy[tags=optionaltyping_var,indent=0]
----
<1> `foo` is declared using an explicit type, `String`
<2> we can call the `toUpperCase` method on a `String`

Groovy will let you write this instead:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/OptionalTypingTest.groovy[tags=optionaltyping_var_def,indent=0]
----
<1> `foo` is declared using `def`
<2> we can still call the `toUpperCase` method, because the type of `aString` is resolved at runtime

So it doesn't matter that you use an explicit type here. It is in particular interesting when you combine this feature
with <<typechecking,static type checking>>, because the type checker performs type inference.

Likewise, Groovy doesn't make it mandatory to declare the types of a parameter in a method:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/OptionalTypingTest.groovy[tags=optionaltyping_orig,indent=0]
----

can be rewritten using `def` as both return type and parameter types, in order to take advantage of duck typing, as
illustrated in this example:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/OptionalTypingTest.groovy[tags=optionaltyping_def,indent=0]
----
<1> both the return type and the parameter types use `def`
<2> it makes it possible to use the method with `String`
<3> but also with `int`s since the `plus` method is defined

TIP: Using the `def` keyword here is recommanded to describe the intent of a method which is supposed to work on any
type, but technically, we could use `Object` instead and the result would be the same: `def` is, in Groovy, strictly
equivalent to using `Object`.

Eventually, the type can be removed altogether from both the return type and the descriptor. But if you want to remove
it from the return type, you then need to add an explicit modifier for the method, so that the compiler can make a difference
between a method declaration and a method call, like illustrated in this example:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/OptionalTypingTest.groovy[tags=optionaltyping_notype,indent=0]
----
<1> if we want to omit the return type, an explicit modifier has to be set.
<2> it is still possible to use the method with `String`
<3> and also with `int`s

TIP: Omitting types is in general considered a bad practice in method parameters or method return types for public APIs.
While using `def` in a local variable is not really a problem because the visibility of the variable is limited to the
method itself, while set on a method parameter, `def` will be converted to `Object` in the method signature, making it
difficult for users to know which is the expected type of the arguments. This means that you should limit this to cases
where you are explicitly relying on duck typing.

[[static-type-checking]]
=== Static type checking

By default, Groovy performs minimal type checking at compile time. Since it is primarily a dynamic language,
most checks that a static compiler would normally do aren't possible at compile time. A method added via runtime
metaprogramming might alter a class or object's runtime behavior. Let's illustrate why in the
following example:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_intro,indent=0]
----
<1> the `Person` class only defines two properties, `firstName` and `lastName`
<2> we can create an instance of Person
<3> and call a method named `formattedName`

It is quite common in dynamic languages for code such as the above example not to throw any error. How can this be?
In Java, this would typically fail at compile time. However, in Groovy, it will not fail at compile time, and if coded
correctly, will also not fail at runtime. In fact, to make this work at runtime, *one* possibility is to rely on
runtime metaprogramming. So just adding this line after the declaration of the `Person` class is enough:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_intro_magic,indent=0]
----

This means that in general, in Groovy, you can't make any assumption about the type of an object beyond its declaration
type, and even if you know it, you can't determine at compile time what method will be called, or which property will
be retrieved, and this is *perfectly fine*. This is how dynamic languages work, and it has a lot of interest.

However, if your program doesn't rely on dynamic features and that you come from the static world (in particular, from
a Java mindset), not catching such "errors" at compile time can be surprising. As we have seen in the previous example,
the compiler cannot be sure this is an error. To make it aware that it is, you have to explicitly instruct the compiler
that you are switching to a type checked mode. This can be done by annotating a class or a method with `@groovy.lang.TypeChecked`.

When type checking is activated, the compiler performs much more work:

* type inference is activated, meaning that even if you use `def` on a local variable for example, the type checker will be
able to infer the type of the variable from the assignments
* method calls are resolved at compile time, meaning that if a method is not declared on a class, the compiler will throw an error
* in general, all the compile time errors that you are used to find in a static language will appear: method not found, property not found,
incompatible types for method calls, number precision errors, ...

In this section, we will describe the behavior of the type checker in various situations and explain the limits of using
`@TypeChecked` on your code.

==== The `@TypeChecked` annotation

The `groovy.lang.TypeChecked` annotation enabled type checking. It can be placed on a class:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=typechecked_class,indent=0]
----

Or on a method:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=typechecked_method,indent=0]
----

In the first case, all methods, properties, fields, inner classes, ... of the annotated class will be type checked, whereas
in the second case, only the method and potential closures or anonymous inner classes that it contains will be type checked.

==== Type checking assignments

An object `o` of type `A` can be assigned to a variable of type `T` if and only if:

* `T` equals `A`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_equals,indent=0]
----
====

* _or_ `T` is one of `String`, `boolean`, `Boolean` or `Class`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_specialcase,indent=0]
----
====

* _or_ `o` is null and `T` is not a primitive type

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_null,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_null2prim,indent=0]
----
====

* _or_ `T` is an array and `A` is an array and the component type of `A` is assignable to the component type of `B`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_array,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_array_fail,indent=0]
----
====

* _or_ `T` is an array and `A` is a list and the component type of `A` is assignable to the component type of `B`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_array_list,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_array_list_fail,indent=0]
----
====

* _or_ `T` is a superclass of `A`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_superclass,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_superclass_fail,indent=0]
----
====

* _or_ `T` is an interface implemented by `A`


+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_interface,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_interface_fail,indent=0]
----
====

* _or_ `T` or `A` are a primitive type and their boxed types are assignable

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_prim,indent=0]
----
====

* _or_ `T` extends `groovy.lang.Closure` and `A` is a SAM-type (single abstract method type)

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_closure_coercion,indent=0]
----
====

* _or_ `T` and `A` derive from `java.lang.Number` and conform to the following table


[cols="1,1,2a"]
.Number types (java.lang.XXX)
[[number-assignment]]
|===
|T |A |Examples

|Double
|Any but BigDecimal or BigInteger
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_double,indent=0]
----

|Float
|Any type but BigDecimal, BigInteger or Double
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_float,indent=0]
----

|Long
|Any type but BigDecimal, BigInteger, Double or Float
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_long,indent=0]
----

|Integer
|Any type but BigDecimal, BigInteger, Double, Float or Long
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_int,indent=0]
----

|Short
|Any type but BigDecimal, BigInteger, Double, Float, Long or Integer
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_short,indent=0]
----

|Byte
|Byte
| [source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_assign_to_byte,indent=0]
----

|===

==== List and map constructors

In addition to the assignment rules above, if an assignment is deemed invalid, in type checked mode, a _list_ literal or a _map_ literal `A` can be assigned
to a variable of type `T` if:

* the assignment is a variable declaration and `A` is a list literal and `T` has a constructor whose parameters match the types of the elements in the list literal
* the assignment is a variable declaration and `A` is a map literal and `T` has a no-arg constructor and a property for each of the map keys

For example, instead of writing:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_ctor_point_classic,indent=0]
----

You can use a "list constructor":

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_ctor_point_list,indent=0]
----

or a "map constructor":

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_ctor_point_map,indent=0]
----

If you use a map constructor, additional checks are done on the keys of the map to check if a property of the same name
is defined. For example, the following will fail at compile time:

[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_ctor_fail,indent=0]
----
<1> The type checker will throw an error `No such property: age for class: Person` at compile time

==== Method resolution

In type checked mode, methods are resolved at compile time. Resolution works by name and arguments. The return type is
irrelevant to method selection. Types of arguments are matched against the types of the parameters following those rules:

An argument `o` of type `A` can be used for a parameter of type `T` if and only if:

* `T` equals `A`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_equals,indent=0]
----
====

* _or_ `T` is a `String` and `A` is a `GString`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_specialcase,indent=0]
----
====

* _or_ `o` is null and `T` is not a primitive type

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_null,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_null2prim,indent=0]
----
====

* _or_ `T` is an array and `A` is an array and the component type of `A` is assignable to the component type of `B`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_array,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_array_fail,indent=0]
----
====

* _or_ `T` is a superclass of `A`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_superclass,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_superclass_fail,indent=0]
----
====

* _or_ `T` is an interface implemented by `A`

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_interface,indent=0]
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_interface_fail,indent=0]
----
====

* _or_ `T` or `A` are a primitive type and their boxed types are assignable

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_argparam_prim,indent=0]
----
====

* _or_ `T` extends `groovy.lang.Closure` and `A` is a SAM-type (single abstract method type)

+

[.result]
====
[source,groovy]
----
include::{projectdir}/src/spec/test/typing/TypeCheckingTest.groovy[tags=stc_arg_closure_coercion,indent=0]
----
====

* _or_ `T` and `A` derive from `java.lang.Number` and conform to the same rules as <<number-assignment,assignment of numbers>>

=== Static compilation (TBD)

