= Object orientation

This chapter covers the object orientation of the Groovy programming language.

== Types (TBD)

=== Primitive types (TBD)

=== Class

Groovy classes are very similar to Java classes, being compatible to those ones at JVM level. They may have methods and fields/properties, which can have the same modifiers (public, protected, private, static, etc) as Java classes.

Here are key differences between Groovy and Java classes:

 * Fields are turned into properties automatically, which results in less verbose codes, whithout so many getters and setter methods. More on this aspect will be covered in the Section "Fields and properties".
 * Their declarations and any property or method without an access modifier are public.
 * Classes do not need to have the same name of the files where they are defined.
 * One file may contain one or more classes (but if a file contains no classes, it is considered a script).

The following code presents an example class.

[source,groovy]
----
include::{projectdir}/src/spec/test/ClassTest.groovy[tags=class_definition,indent=0]
----
<1> class opening, with the name `Person`
<2> string field and property named `name`
<3> method definition


==== Normal class (MichaelSchuenck)

Normal classes refer to classes which are top level and concrete. This means they can be instantiated whithout restrictions from any other classes or scripts. This way, they can only be public (even though the `public` keyword may be supressed). Classes are instantiated by calling their constructors, using the `new` keywork.

[source,groovy]
----
include::{projectdir}/src/spec/test/ClassTest.groovy[tags=class_instantiation,indent=0]
----

==== Static class (MichaelSchuenck)

If a class contains only static members (fields

==== Inner class (MichaelSchuenck)
===== Anonymous inner class (MichaelSchuenck)
==== Abstract class (MichaelSchuenck)

=== Interface (TBD)

=== Annotation (TBD)

==== Closure annotation parameters (TBD)
==== Meta-annotations (TBD)
==== Annotation placement (TBD)

=== Constructors (TBD)

==== Named argument constructor (TBD)

=== Methods (TBD)

==== Method definition (TBD)
==== Named arguments (TBD)
==== Default arguments (TBD)
==== Varargs (TBD)
==== Method selection algorithm (TBD)
==== Exception declaration (TBD)

=== Fields and properties (TBD)

==== Fields (TBD)
==== Properties (TBD)

=== Inheritance (TBD)

[[generics]]
=== Generics (TBD)

include::{projectdir}/src/spec/doc/core-traits.adoc[leveloffset=+1]

