= Getting started
:toc:
:icons: font
:linkcss!:

== Download

In this download area, you will be able to download the distribution (binary and source), the Windows installer (for some of the versions) and the documentation for **Groovy**.

For a quick and effortless start on Mac OSX, Linux or Cygwin, you can use link:http://gvmtool.net[GVM] (the Groovy enVironment Manager) to download and configure any **Groovy** version of your choice. Basic (TODO)[instructions] can be found below.

=== Groovy 2.1

==== Groovy 2.1.6

==== Groovy 2.1.5

=== Groovy 2.2

==== Groovy 2.2.0-beta-1

=== Groovy 2.0

==== Groovy 2.0.8

=== Groovy 1.8 (Maintenance Release)

==== Groovy 1.8.9

=== Snapshots

=== Older Releases

==== Groovy 1.7.11

==== Groovy 1.6.9

==== Groovy 1.5.8

=== Legacy Groovy 1.0


== Maven Repositories

=== Groovy 2.0.X  and newer

=== Groovy 1.6.X - 1.8.X

=== Groovy 1.1.X - 1.5.X

=== Groovy 1.0

=== Snapshot Releases


== GVM (the Groovy enVironment Manager)


== Other ways to get Groovy

=== Installation on Mac OS X

==== MacPorts

Set up link:http://www.macports.org[MacPorts] and type in the Terminal:

[source,shell]
----
sudo port install groovy
----

==== Homebrew

=== Installation on Windows

=== Other Distributions

=== Source Code

== IDE plugin


== Install Binary

These instructions describe how to install a binary distribution of **Groovy**.

* First, link:#download-groovy[Download] a binary distribution of Groovy and unpack it into some file on your local file system.
* Set your ++GROOVY_HOME++ environment variable to the directory you unpacked the distribution.
* Add ++GROOVY_HOME/bin++ to your ++PATH++ environment variable.
* Set your ++JAVA_HOME++ environment variable to point to your JDK. On OS X this is ++/Library/Java/Home++, on other unixes its often ++/usr/java++ etc. If you've already installed tools like Ant or Maven you've probably already done this step.

You should now have Groovy installed properly. You can test this by typing the following in a command shell:

[source,shell]
----
groovysh
----

Which should create an interactive groovy shell where you can type Groovy statements. Or to run the link:tools/tools-groovyconsole.html[Swing interactive console] type:

[source,shell]
----
groovyConsole
----

To run a specific Groovy script type:

[source,shell]
----
groovy SomeScript.groovy
----
