//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= Composite Pattern

The https://en.wikipedia.org/wiki/Composite_pattern[Composite Pattern] allows you to treat single instances of an object the same way as a group of objects. The pattern is often used with hierarchies of objects. Typically, one or more methods should be callable in the same way for either __leaf__ or __composite__ nodes within the hierarchy. In such a case, composite nodes typically invoke the same named method for each of their children nodes.

== Example

Consider this usage of the composite pattern where we want to call `toString()` on either `Leaf` or `Composite` objects.

[plantuml, CompositeClasses, png]
....
skinparam linetype ortho
skinparam nodesep 100
class Component {
    +toString()
}
class Leaf {
    +toString()
}
class Composite {
    +toString()
}
object componentClient
hide fields
componentClient ..r..> "<<use>>" Component
Component <|-- Leaf
Composite "1" *-- "*" Component : children
Component <|-- Composite
....

In Java, the `Component` class is essential as it provides the type used for both leaf and composite nodes. In Groovy, because of duck-typing, we don't need it for that purpose, however, it can still serve as a useful place to place common behaviour between the leaf and composite nodes.

For our purposes, we will assemble the following hierarchy of components.

[plantuml, CompositeComponents, png]
....
object root
object "leaf A" as leafA
object "comp B" as compB
object "leaf C" as leafC
object "leaf B1" as leafB1
object "leaf B2" as leafB2

root -- leafA
root -- compB
root -- leafC
compB -- leafB1
compB -- leafB2
....

Here is the code:

[source,groovy]
----
include::../test/DesignPatternsTest.groovy[tags=composite_code,indent=0]
----

Here is the resulting output:

----
root
-leaf A
-comp B
--leaf B1
--leaf B2
-leaf C
----