/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.codehaus.groovy.tools

import groovy.json.JsonSlurper
import groovy.lang.Closure
import groovy.lang.GString
import org.codehaus.groovy.reflection.GeneratedMetaMethod
import org.codehaus.groovy.runtime.DefaultGroovyMethods
import org.codehaus.groovy.runtime.DefaultGroovyStaticMethods
import org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl
import org.codehaus.groovy.vmplugin.v8.IndyInterface
import org.junit.jupiter.api.Test

import java.lang.reflect.Modifier

/**
 * The GraalVM reachability metadata the groovy jar ships for its own runtime
 * (GROOVY-12365): generated by the build, so these tests check the
 * generator's contract rather than a hand-maintained file.
 */
final class NativeImageMetadataTest {

    private static final String RESOURCE = NativeImageMetadataGenerator.METADATA_DIRECTORY + '/' + NativeImageMetadataGenerator.METADATA_FILE
    private static final ClassLoader LOADER = DefaultGroovyMethods.classLoader

    private static URL resource() {
        URL url = LOADER.getResource(RESOURCE)
        assert url != null : "metadata not on the class path: $RESOURCE"
        url
    }

    private static List<Map> reflection() {
        (new JsonSlurper().parse(resource()) as Map).reflection as List<Map>
    }

    private static final String REGISTRY = MetaClassRegistryImpl.name
    private static final String INDY = IndyInterface.name

    /** Entries conditional on the registry: the bootstrap and everything metaclass creation needs. */
    private static List<Map> bootstrapEntries() {
        reflection().findAll { it.condition.typeReached == REGISTRY }
    }

    /** Full member registration of a Groovy-owned type, conditional on that type. */
    private static List<Map> memberEntries() {
        reflection().findAll { it.allDeclaredFields }
    }

    /** The classes probed for by naming convention that are expected not to exist. */
    private static List<Map> negativeEntries() {
        reflection().findAll { String t = it.type; t.endsWith('BeanInfo') || t.endsWith('Customizer') || t.startsWith('groovy.runtime.metaclass.') }
    }

    private static List<Class> receivers() {
        GeneratedMetaMethod.DgmMethodRecord.loadDgmInfo().collect { it.parameters[0] }.findAll { !it.array && !it.primitive }.unique()
    }

    @Test
    void shippedFileIsWhatTheGeneratorProducesForThisRuntime() {
        def records = GeneratedMetaMethod.DgmMethodRecord.loadDgmInfo()
        assert resource().text == NativeImageMetadataGenerator.generate(records)
    }

    @Test
    void everyEntryIsConditionalOnAGroovyTypeBeingReached() {
        def entries = reflection()
        assert !entries.isEmpty()
        entries.each { Map entry ->
            String reached = entry.condition?.typeReached
            assert reached : "unconditional entry: $entry"
            assert NativeImageMetadataGenerator.isGroovyOwned(reached) : "condition on a foreign type: $entry"
        }
    }

    @Test
    void registryBootstrapReflectionIsConditionalOnTheRegistry() {
        def bootstrap = bootstrapEntries()
        Set<String> types = bootstrap*.type as Set
        // the classes whose static methods are scanned, and the meta-method classes instantiated
        assert types.containsAll([
                'org.codehaus.groovy.runtime.DefaultGroovyMethods',
                'org.codehaus.groovy.runtime.DefaultGroovyStaticMethods',
                'org.codehaus.groovy.runtime.ArrayGroovyMethods',
                'org.codehaus.groovy.vmplugin.v8.PluginDefaultGroovyMethods',
                'org.codehaus.groovy.runtime.dgmimpl.NumberNumberPlus',
        ])
        bootstrap.findAll { it.type.endsWith('NumberNumberPlus') }.each { assert it.allDeclaredConstructors }
        // every abstract type in the records is asked for its methods by the SAM check, JDK ones
        // included, and so are the abstract supertypes the check walks
        def abstractReceivers = receivers().findAll { Modifier.isAbstract(it.modifiers) }*.name as Set
        assert 'java.util.List' in abstractReceivers && 'groovy.lang.Closure' in abstractReceivers
        assert types.containsAll(abstractReceivers)
        assert types.containsAll(['java.lang.Readable', 'java.lang.AutoCloseable', 'java.io.Closeable'])
        // signatures of the holders scanned reflectively (the plugin DGM classes) are cached too
        assert types.containsAll(['java.util.function.IntFunction', 'java.util.OptionalInt'])
        // and the hierarchy of every type that gets a metaclass: superclasses with members, interfaces SAM-checked
        assert types.containsAll(['groovy.lang.MutableMetaClass', 'java.lang.Runnable', 'java.util.AbstractList', 'java.lang.Object'])
        bootstrap.find { it.type == 'java.util.AbstractList' }.with { assert it.allDeclaredMethods && it.allDeclaredFields }
        bootstrap.find { it.type == 'java.lang.Runnable' }.with { assert it.allPublicMethods && !it.allDeclaredFields }
        // interfaces of concrete cached types are SAM-checked too, and superclasses of scanned holders scanned
        bootstrap.find { it.type == 'java.lang.reflect.Type' }.with { assert it.allPublicMethods }
        bootstrap.find { it.type == 'org.codehaus.groovy.runtime.DefaultGroovyMethodsSupport' }.with { assert it.allDeclaredMethods }
        bootstrap.find { it.type == 'org.codehaus.groovy.runtime.GeneratedClosure' }.with { assert it.allPublicMethods }
        assert bootstrap.find { it.type == 'org.codehaus.groovy.runtime.DgmProxyFactory' }.keySet() == ['condition', 'type'] as Set
        // JDK 21 supertypes of record types, listed by name since the build may run on JDK 17
        bootstrap.find { it.type == 'java.util.SequencedCollection' }.with { assert it.allPublicMethods }
        bootstrap.findAll { it.type in abstractReceivers }.each { assert it.allPublicMethods && it.allDeclaredMethods }
        // every other type in the records is loaded by name, and needs no more than that
        def concreteJdk = receivers().findAll { !Modifier.isAbstract(it.modifiers) && it.name.startsWith('java.') }*.name
        assert !concreteJdk.isEmpty()
        assert types.containsAll(concreteJdk)
        ['java.lang.String', 'java.io.File'].each { name ->
            assert bootstrap.find { it.type == name }.keySet() == ['condition', 'type'] as Set : name
        }
    }

    @Test
    void indyLookupTargetsAreConditionalOnTheIndyBootstrap() {
        def indy = reflection().findAll { it.condition.typeReached == INDY }
        Set<String> types = indy*.type as Set
        assert types.containsAll([
                'org.codehaus.groovy.vmplugin.v8.IndyInterface',
                'org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures',
                'org.codehaus.groovy.vmplugin.v8.IndyMath',
                'groovy.lang.MetaObjectProtocol',
                'org.codehaus.groovy.runtime.InvokerHelper',
                'java.lang.Number',
                'java.math.BigDecimal',
        ])
        assert indy.find { it.type == 'java.util.Objects' }.methods == [[name: 'nonNull', parameterTypes: ['java.lang.Object']]]
        indy.findAll { !(it.type in ['java.lang.Class', 'java.util.Objects']) }.each { assert it.allDeclaredMethods && it.allPublicMethods && it.allDeclaredConstructors : it }
        assert !types.any { it.startsWith('java.util.function.') }
        // java.lang.Class is registered method by method, not wholesale
        def clazz = indy.find { it.type == 'java.lang.Class' }
        assert clazz.methods == [[name: 'forName', parameterTypes: ['java.lang.String', 'boolean', 'java.lang.ClassLoader']]]
        assert !clazz.allPublicMethods
    }

    @Test
    void groovyOwnedDgmReceiversHaveTheirMembersRegistered() {
        Set<String> registered = memberEntries()*.type as Set
        def groovyReceivers = receivers().findAll { NativeImageMetadataGenerator.isGroovyOwned(it.name) }*.name as Set
        assert !groovyReceivers.isEmpty()
        assert 'groovy.lang.Closure' in groovyReceivers
        assert registered.containsAll(groovyReceivers)
        memberEntries().findAll { !it.type.startsWith('java.') }.each { Map entry ->
            assert entry.condition.typeReached == REGISTRY
            assert NativeImageMetadataGenerator.isGroovyOwned(entry.type as String)
            assert entry.allDeclaredConstructors && entry.allDeclaredMethods && entry.allDeclaredFields && entry.allPublicMethods
        }
    }

    @Test
    void asyncRuntimeLookupsAreRegisteredByName() {
        def executors = reflection().findAll { it.type == 'java.util.concurrent.Executors' }
        assert executors*.condition*.typeReached as Set == ['org.apache.groovy.runtime.async.AsyncExecutors', 'org.apache.groovy.runtime.async.DefaultPool'] as Set
        executors.each { assert it.methods == [[name: 'newVirtualThreadPerTaskExecutor', parameterTypes: []]] }
        def scoped = reflection().find { it.type == 'java.lang.ScopedValue' }
        assert scoped.condition.typeReached == 'org.apache.groovy.runtime.async.ScopedLocal'
        assert scoped.methods*.name as Set == ['newInstance', 'get', 'isBound', 'where'] as Set
    }

    @Test
    void jdkTypesAppearOnlyOnTheRuntimesOwnBehalf() {
        def runtimeFamilies = [REGISTRY, INDY, 'org.codehaus.groovy.reflection.ReflectionUtils',
                               'org.apache.groovy.runtime.async.AsyncExecutors', 'org.apache.groovy.runtime.async.DefaultPool',
                               'org.apache.groovy.runtime.async.ScopedLocal']
        reflection().each { Map entry ->
            String type = entry.type
            if (!NativeImageMetadataGenerator.isGroovyOwned(type)) {
                assert entry.condition.typeReached in runtimeFamilies : "foreign type outside the runtime's own families: $entry"
            }
        }
        Set<String> types = reflection()*.type as Set
        assert !types.any { it.startsWith('groovy.runtime.metaclass.java.') }
    }

    @Test
    void negativeLookupsAccompanyEveryIntrospectedType() {
        def negatives = negativeEntries()
        assert !negatives.isEmpty()
        Set<String> names = negatives*.type as Set
        assert 'groovy.runtime.metaclass.org.codehaus.groovy.runtime.DefaultGroovyMethodsMetaClass' in names
        assert names.containsAll(['groovy.lang.ClosureBeanInfo', 'groovy.lang.ClosureCustomizer',
                                  'groovy.runtime.metaclass.groovy.lang.ClosureMetaClass',
                                  // the Introspector walks the superclass chain
                                  'groovy.lang.GroovyObjectSupportBeanInfo', 'java.lang.ObjectBeanInfo', 'java.lang.ObjectCustomizer'])
        // but the custom metaclass lookup is for the type itself only
        assert !('groovy.runtime.metaclass.java.lang.ObjectMetaClass' in names)
        negatives.each { Map entry ->
            assert entry.keySet() == ['condition', 'type'] as Set : "negative entries carry no member flags: $entry"
            assert entry.condition.typeReached == REGISTRY
        }
    }

    @Test
    void bootstrapRuntimeTypesAreRegistered() {
        Set<String> registered = memberEntries()*.type as Set
        assert registered.containsAll([
                'groovy.lang.GroovySystem',
                'org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl',
                'org.codehaus.groovy.runtime.NullObject',
                'groovy.lang.Script',
                'groovy.lang.IntRange',
                'org.codehaus.groovy.runtime.GStringImpl',
                'org.codehaus.groovy.runtime.CurriedClosure',
                'groovy.lang.Reference',
                Closure.IDENTITY.class.name,
                GString.EMPTY.class.name,
        ])
        assert NativeImageMetadataGenerator.INTROSPECTED_ANONYMOUS_TYPES as Set == [Closure.IDENTITY.class.name, GString.EMPTY.class.name] as Set
    }

    @Test
    void extensionModuleMetadataCoversTheClassesTheRegistryLoadsAndScans() {
        // stand-ins for a module's extension classes: static-method holders with JDK types in their signatures
        def json = NativeImageMetadataGenerator.generateForModule([DefaultGroovyStaticMethods], [DefaultGroovyStaticMethods])
        def entries = (new JsonSlurper().parseText(json) as Map).reflection as List<Map>
        assert entries.every { it.condition.typeReached == REGISTRY }
        def holder = entries.find { it.type == DefaultGroovyStaticMethods.name }
        assert holder.allDeclaredMethods && holder.allDeclaredConstructors
        // a type from a static method's signature is cached by the registry, an abstract one SAM-checked
        assert entries.find { it.type == 'java.lang.Runnable' }?.allPublicMethods
        // nothing else: no negatives, no indy family, no DGM records
        assert !entries.any { it.type.endsWith('BeanInfo') }
        assert !entries.any { it.condition.typeReached == INDY }
    }

    @Test
    void xmlModuleMetadataCoversFactorySupportsJaxpLookups() {
        // groovy-xml's FactorySupport asks ServiceLoader for each JAXP factory (a resource read an
        // exact-mode image must allow though the JDK ships no such file) and then instantiates the
        // JDK default implementation by name; both are conditional on FactorySupport being reached
        def parsed = new JsonSlurper().parseText(NativeImageMetadataGenerator.generateForModule('groovy-xml', [], [])) as Map
        def resources = parsed.resources as List<Map>
        assert resources*.glob as Set == [
                'META-INF/services/javax.xml.parsers.SAXParserFactory',
                'META-INF/services/javax.xml.parsers.DocumentBuilderFactory',
                'META-INF/services/javax.xml.stream.XMLInputFactory',
                'META-INF/services/javax.xml.transform.TransformerFactory',
                'META-INF/services/javax.xml.validation.SchemaFactory',
                'META-INF/services/javax.xml.xpath.XPathFactory',
        ] as Set
        assert resources.every { it.condition.typeReached == 'groovy.xml.FactorySupport' }
        def sax = (parsed.reflection as List<Map>).find { it.type == 'com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl' }
        assert sax.condition.typeReached == 'groovy.xml.FactorySupport'
        assert sax.methods*.name == ['<init>']

        // other modules get no resources section at all
        assert !(new JsonSlurper().parseText(NativeImageMetadataGenerator.generateForModule('groovy-nio', [], [])) as Map).containsKey('resources')
    }

    @Test
    void concurrentJavaModuleMetadataCarriesTheAsyncRuntimeFamily() {
        // GROOVY-12380: the Java-only jar replaces the groovy jar, whose metadata carries this family
        def entries = (new JsonSlurper().parseText(NativeImageMetadataGenerator.generateForModule('groovy-concurrent-java', [], [])) as Map).reflection as List<Map>
        def executors = entries.findAll { it.type == 'java.util.concurrent.Executors' }
        assert executors*.condition*.typeReached as Set == ['org.apache.groovy.runtime.async.AsyncExecutors', 'org.apache.groovy.runtime.async.DefaultPool'] as Set
        assert executors.every { it.methods*.name == ['newVirtualThreadPerTaskExecutor'] }
        def scopedValue = entries.find { it.type == 'java.lang.ScopedValue' }
        assert scopedValue.condition.typeReached == 'org.apache.groovy.runtime.async.ScopedLocal'
        assert scopedValue.methods*.name as Set == ['newInstance', 'get', 'isBound', 'where'] as Set
        assert entries.find { it.type == 'java.lang.ScopedValue$Carrier' }?.methods*.name == ['run']
        // nothing that needs the groovy jar: no registry family
        assert !entries.any { it.condition.typeReached == REGISTRY }
    }

    @Test
    void entriesAreUnique() {
        def keys = reflection().collect { [it.condition.typeReached, it.type] }
        assert keys.size() == (keys as Set).size()
    }
}
