/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.groovy.lang.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

import static java.lang.annotation.ElementType.CONSTRUCTOR;
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.CLASS;

/**
 * Marks a program element as part of Groovy's binary ABI.
 * <p>
 * Elements annotated with {@code @GroovyABI} may be referenced directly by
 * bytecode generated by the Groovy compiler. Their signatures and semantics
 * therefore form part of the compatibility contract between compiled Groovy
 * classes and the Groovy runtime.
 * <p>
 * Changes to annotated elements must preserve binary compatibility with
 * previously compiled Groovy code unless the corresponding compatibility
 * guarantee is intentionally dropped.
 * <p>
 * This annotation is intended only for members that are referenced by
 * bytecode which may outlive the compiler version that produced it. Members
 * used exclusively by bytecode generated at runtime by the current Groovy
 * version should not be annotated.
 * <p>
 * Prefer annotating the type when every reachable member shares the same
 * {@link #since()} value; annotate members individually only when their
 * {@code since} differs or only part of the type is part of the ABI.
 *
 * <p>{@code since} records the first Groovy release in which the element
 * became part of the binary ABI. It is mandatory and must use the full
 * three-part version form, e.g. {@code "1.0.0"}.
 *
 * <p><b>Retention.</b> This marker has {@link java.lang.annotation.RetentionPolicy#CLASS}
 * retention: it survives into published class files so the build's binary
 * compatibility tooling can rely on it.
 *
 * <p>Notes:
 * <li>groovy.*: These classes are part of the public API and are therefore not annotated.
 * <li>runtime packages: These classes are normally internal and subject to
 * removal or change. If any of their methods is referenced by the compiler,
 * it must be annotated so the reference becomes visible.
 * <li>AST helper classes not in runtime: Some AST transforms leverage helper
 * classes that are not in a runtime package. These classes must be annotated.
 */
@Documented
@Target({TYPE, METHOD, CONSTRUCTOR, FIELD})
@Retention(CLASS)
public @interface GroovyABI {
    String since();
}
