/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 */
package org.apache.groovy.ginq.provider.sql.runtime;

import groovy.sql.GroovyRowResult;
import groovy.sql.Sql;
import org.apache.groovy.ginq.provider.collection.runtime.Queryable;
import org.apache.groovy.lang.annotation.Incubating;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

/**
 * Executes the SQL generated by the native SQL provider. The generated code
 * calls {@link #execute(Object, String, List)} with the compile-time constant
 * SQL text and the runtime parameter values.
 *
 * @since 6.0.0
 */
@Incubating
public final class SqlGinqRuntime {
    /**
     * Runs the supplied SQL with the supplied bound parameters against the
     * supplied data source and returns the rows as a {@code Queryable}.
     * <p>
     * The data source may be a {@link Sql} instance or {@link Connection}
     * (used as-is; the caller owns their lifecycle), or a {@link DataSource}
     * (a connection is borrowed and released per query).
     *
     * @param dataSource the data source to query
     * @param sqlText the SQL text with {@code ?} placeholders
     * @param params the parameter values in placeholder order
     * @return the resulting rows
     * @throws SQLException if the query fails
     */
    public static Queryable<GroovyRowResult> execute(Object dataSource, String sqlText, List<Object> params) throws SQLException {
        if (dataSource instanceof Sql) {
            return Queryable.from(((Sql) dataSource).rows(sqlText, params));
        }
        if (dataSource instanceof DataSource) {
            Sql sql = new Sql((DataSource) dataSource);
            try {
                return Queryable.from(sql.rows(sqlText, params));
            } finally {
                sql.close();
            }
        }
        if (dataSource instanceof Connection) {
            return Queryable.from(new Sql((Connection) dataSource).rows(sqlText, params));
        }
        throw new IllegalArgumentException("Unsupported dataSource: expected a groovy.sql.Sql, javax.sql.DataSource or java.sql.Connection but got: "
                + (dataSource == null ? "null" : dataSource.getClass().getName()));
    }

    /**
     * Builds a {@code LIKE} pattern from a runtime value, escaping the
     * wildcard characters {@code %} and {@code _} (and the escape character
     * itself) with {@code !}, matching the {@code ESCAPE '!'} clause the
     * renderer emits. Used for {@code contains}/{@code startsWith}/{@code endsWith}.
     *
     * @param value the value to match literally
     * @param matchBefore whether anything may precede the value
     * @param matchAfter whether anything may follow the value
     * @return the escaped pattern
     */
    public static String likePattern(Object value, boolean matchBefore, boolean matchAfter) {
        String escaped = String.valueOf(value)
                .replace("!", "!!")
                .replace("%", "!%")
                .replace("_", "!_");
        return (matchBefore ? "%" : "") + escaped + (matchAfter ? "%" : "");
    }

    private SqlGinqRuntime() {
    }
}
