== JUnit 5

Much of the approach and helper classes described under JUnit4 apply when using JUnit5 however JUnit5
uses some slightly different class annotations when writing your tests. See the http://junit.org[JUnit5] documentation
for more details.

Create your test classes as per normal JUnit5 guidelines as shown in this example:

[source,groovy]
----
include::{rootprojectdir}/subprojects/groovy-test-junit5/src/spec/test/MyTestViaRun.groovy[tags=junit5_test_part1,indent=0]
include::{rootprojectdir}/subprojects/groovy-test-junit5/src/spec/test/MyTestViaRun.groovy[tags=junit5_test_part2,indent=0]
----
<1> This test requires the additional `org.junit.jupiter:junit-jupiter-params` dependency if not already in your project.

You can run the tests in your IDE or build tool if it supports and is configured for JUnit5.
If you run the above test in the GroovyConsole or via the `groovy` command, you will see a short text summary of the
result of running the test:

----
include::{rootprojectdir}/subprojects/groovy-test-junit5/src/spec/test/MyTestViaRun.groovy[tags=junit5_test_output,indent=0]
----

More detailed information is available at the `FINE` logging level. You can configure your logging to display such
information or do it programmatically as follows:

[source,groovy]
----
include::{rootprojectdir}/subprojects/groovy-test-junit5/src/spec/test/MyTestViaRun.groovy[tags=junit5_test_part3,indent=0]
----
