//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= JsonBuilder

Groovy's `JsonBuilder` makes it easy to create Json. For example to create this Json string:

[source,groovy]
----
include::../test/json/JsonBuilderTest.groovy[tags=json_string,indent=0]
----

you can use a `JsonBuilder` like this:

[source,groovy]
----
include::../test/json/JsonBuilderTest.groovy[tags=json_builder,indent=0]
----

We use https://github.com/lukas-krecan/JsonUnit[JsonUnit] to check that the builder produced the expected result:

[source,groovy]
----
include::../test/json/JsonBuilderTest.groovy[tags=json_assert,indent=0]
----

If you need to customize the generated output you can pass a `JsonGenerator` instance when creating a `JsonBuilder`:

[source,groovy]
----
include::../test/json/JsonBuilderTest.groovy[tags=json_builder_generator,indent=0]
----
