//////////////////////////////////////////

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.

//////////////////////////////////////////

= StreamingJsonBuilder

Unlike `JsonBuilder` which creates a data structure in memory, which is handy in those situations where you want to alter the structure programmatically before output,
`StreamingJsonBuilder` directly streams to a writer without any intermediate memory data structure.
If you do not need to modify the structure and want a more memory-efficient approach, use `StreamingJsonBuilder`.

The usage of `StreamingJsonBuilder` is similar to `JsonBuilder`. In order to create this Json string:

[source,groovy]
----
include::../test/json/StreamingJsonBuilderTest.groovy[tags=json_string,indent=0]
----

you use a `StreamingJsonBuilder` like this:

[source,groovy]
----
include::../test/json/StreamingJsonBuilderTest.groovy[tags=streaming_json_builder,indent=0]
----

We use https://github.com/lukas-krecan/JsonUnit[JsonUnit] to check the expected result:

[source,groovy]
----
include::../test/json/StreamingJsonBuilderTest.groovy[tags=json_assert,indent=0]
----

If you need to customize the generated output you can pass a `JsonGenerator` instance when creating a `StreamingJsonBuilder`:

[source,groovy]
----
include::../test/json/StreamingJsonBuilderTest.groovy[tags=streaming_json_builder_generator,indent=0]
----
